<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<div class="alert alert-error">
<h2>Die aufgerufene Seite wurde nicht gefunden.</h2>
<?php 
    if (isset($this->reason) && $this->reason) {
        switch ($this->reason) {
            case 'error-controller-cannot-dispatch':
                $reasonMessage = 'Der angeforderte Controller war nicht in der Lage die Anfrage zu verarbeiten.';
                break;
            case 'error-controller-not-found':
                $reasonMessage = 'Der angeforderte Controller konnte keiner Controller Klasse zugeordnet werden.';
                break;
            case 'error-controller-invalid':
                $reasonMessage = 'Der angeforderte Controller ist nicht aufrufbar.';
                break;
            case 'error-router-no-match':
                $reasonMessage = 'Für die angeforderte URL konnte keine Übereinstimmung gefunden werden.';
                break;
            default:
                $reasonMessage = 'Zu diesem Zeitpunkt ist es uns nicht möglich zu bestimmen, warum ein 404 Fehler aufgetreten ist.';
                break;
        }
        
        echo '<p>' . $reasonMessage . '</p>';
    }
?>
</div>

<div class="well">
<h3>Weitere Informationen</h3>
<table class="table">
<?php if (isset($this->controller) && $this->controller): ?>
<tr>
<th>Controller</th>
<td><?php echo $this->escapeHtml($this->controller) ?> <?php echo (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller) ? '(' . sprintf(('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')' : ''; ?></td>
</tr>
<?php endif ?>
<?php if (isset($this->exception) && $this->exception): ?>
<tr>
<th>Exception</th>
<td><?php echo get_class($this->exception); ?></td>
</tr>
<tr>
<th>Datei</th>
<td><pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre></td>
</tr>
<tr>
<th>Meldung</th>
<td><pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre></td>
</tr>
<tr>
<th>Stack&nbsp;Trace</th>
<td><pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre></td>
</tr>
<?php endif ?>
</table>
</div>
