<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 3.2 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 3.2</h1>
<h3>Virtual Host Konfiguration für Windows</h3>
<pre>
&lt;VirtualHost *:80&gt;
   DocumentRoot "D:/devhost/luigis-pizza.local/public"
   ServerName luigis-pizza.local

   &lt;Directory "D:/devhost/luigis-pizza.local/public"&gt;
       Options Indexes MultiViews FollowSymLinks
       AllowOverride All
       Order allow,deny
       Allow from all
   &lt;/Directory&gt;
&lt;/VirtualHost&gt; 
</pre>
</div>
</div>
