<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 3.4 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 3.4</h1>
<h3>Ausgabe nach der Installation von <code>Zend\Mvc</code> mit Pyrus</h3>
<pre>
Using PEAR installation found at /home/devhost/luigis-pizza.local
Downloading packages.zendframework.com/Zend_Mvc
Downloading packages.zendframework.com/Zend_Console
Downloading packages.zendframework.com/Zend_Di
Downloading packages.zendframework.com/Zend_Code
Downloading packages.zendframework.com/Zend_ModuleManager
Downloading packages.zendframework.com/Zend_Config
Downloading packages.zendframework.com/Zend_Http
Downloading packages.zendframework.com/Zend_Uri
Downloading packages.zendframework.com/Zend_Escaper
Downloading packages.zendframework.com/Zend_Validator
Downloading packages.zendframework.com/Zend_I18n
Downloading packages.zendframework.com/Zend_Filter
Downloading packages.zendframework.com/Zend_Crypt
Downloading packages.zendframework.com/Zend_Db
Downloading packages.zendframework.com/Zend_Math
Downloading packages.zendframework.com/Zend_ServiceManager
Installed packages.zendframework.com/Zend_Mvc-2.1.3
Installed packages.zendframework.com/Zend_Console-2.1.3
Installed packages.zendframework.com/Zend_Di-2.1.3
Installed packages.zendframework.com/Zend_ModuleManager-2.1.3
Installed packages.zendframework.com/Zend_Http-2.1.3
Installed packages.zendframework.com/Zend_Uri-2.1.3
Installed packages.zendframework.com/Zend_ServiceManager-2.1.3
Installed packages.zendframework.com/Zend_Code-2.1.3
Installed packages.zendframework.com/Zend_Config-2.1.3
Installed packages.zendframework.com/Zend_Escaper-2.1.3
Installed packages.zendframework.com/Zend_Validator-2.1.3
Installed packages.zendframework.com/Zend_I18n-2.1.3
Installed packages.zendframework.com/Zend_Db-2.1.3
Installed packages.zendframework.com/Zend_Math-2.1.3
Installed packages.zendframework.com/Zend_Filter-2.1.3
Installed packages.zendframework.com/Zend_Crypt-2.1.3
</pre>
</div>
</div>
