<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 3.1 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 3.1</h1>
<h3>Virtual Host Konfiguration für Linux</h3>
<pre>
&lt;VirtualHost *&gt;
    ServerName luigis-pizza.local
    DocumentRoot /home/devhost/luigis-pizza.local/public/
    AccessFileName .htaccess

    &lt;Directory /home/devhost/luigis-pizza.local/public/&gt;
        DirectoryIndex index.php
        AllowOverride All
        Order allow,deny
        Allow from all
    &lt;/Directory&gt;
&lt;/VirtualHost&gt;
</pre>
</div>
</div>
