<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 3.3 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 3.3</h1>
<h3>Ausgabe nach der Installation von <code>Zend\View</code> mit Pyrus</h3>
<pre>
Using PEAR installation found at /home/devhost/luigis-pizza.local
Downloading packages.zendframework.com/Zend_View
Downloading packages.zendframework.com/Zend_EventManager
Downloading packages.zendframework.com/Zend_Loader
Downloading packages.zendframework.com/Zend_Stdlib
Installed packages.zendframework.com/Zend_View-2.1.3
Installed packages.zendframework.com/Zend_EventManager-2.1.3
Installed packages.zendframework.com/Zend_Loader-2.1.3
Installed packages.zendframework.com/Zend_Stdlib-2.1.3
Optional dependencies that will not be installed, use --optionaldeps:
packages.zendframework.com/Zend_Filter depended on by packages.zendframework.com/Zend_View
</pre>
</div>
</div>
