<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 3.6 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 3.6</h1>
<h3>Ausgabe nach der Installation mit Composer</h3>
<pre>
Loading composer repositories with package information
Installing dependencies
  - Installing zendframework/zend-stdlib (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-loader (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-eventmanager (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-view (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-servicemanager (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-filter (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-i18n (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-validator (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-escaper (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-uri (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-http (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-modulemanager (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-code (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-di (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-console (2.1.3)
    Downloading: 100%

  - Installing zendframework/zend-mvc (2.1.3)
    Downloading: 100%

zendframework/zend-stdlib suggests installing pecl-weakref (Implementation of weak references for Stdlib\CallbackHandler)
zendframework/zend-filter suggests installing zendframework/zend-crypt (Zend\Crypt component)
zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-validator suggests installing zendframework/zend-math (Zend\Math component)
zendframework/zend-modulemanager suggests installing zendframework/zend-config (Zend\Config component)
zendframework/zend-code suggests installing doctrine/common (Doctrine\Common >=2.1 for annotation features)

Writing lock file
Generating autoload files
</pre>
</div>
</div>
