<?php
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Footer view script
 * 
 * @package    Application
 */
?>
<footer>
<div class="container">
<div class="row">
<div class="span3">
<h4>Service</h4>
<ul class="unstyled">
<li><a href="http://www.zendframeworkbuch.de/about">Über das Buch</a></li>
<li><a href="http://www.zendframeworkbuch.de/about/author">Über den Autor</a></li>
<li><a href="http://www.zendframeworkbuch.de/about/contact">Feedback</a></li>
<li><a href="http://www.zendframeworkbuch.de/about/privacy">Datenschutz</a></li>
<li><a href="http://www.zendframeworkbuch.de/about/imprint">Impressum</a></li>
</ul>
</div>
<div class="span3">
<h4>Zend Framework 2</h4>
<ul class="unstyled">
<li><a href="http://framework.zend.com/" target="_blank">Zend Framework 2 Website</a></li>
<li><a href="http://zf2.readthedocs.org/" target="_blank">Zend Framework 2 Dokumentation</a></li>
<li><a href="http://www.zendframeworkmagazin.de/" target="_blank">Zend Framework Magazin</a> <span class="label label-success">Cool ;-)</span></li>
</ul>
</div>
<div class="span3">
<h4>Social Media</h4>
<ul class="unstyled">
<li><a href="http://www.zendframeworkbuch.de/blog/rss"><i class="icon-rss"></i>RSS Feed</a></li>
<li><a href="https://www.facebook.com/zendframework2buch" target="_blank"><i class="icon-facebook"></i>Facebook Fanseite</a></li>
<li><a href="https://plus.google.com/117394840563518489304" rel="publisher" target="_blank"><i class="icon-google-plus"></i>Google+ Seite</a> <span class="label label-important">Tipp!</span></li>
<li><a href="https://twitter.com/ZFMagazin" target="_blank"><i class="icon-twitter"></i>Twitter</a></li>
<li><a href="https://www.amazon.de/registry/wishlist/3UI4K2KFRJY0T/" target="_blank"><i class="icon-gift"></i> Amazon Wunschliste</a></li>
</ul>
</div>
<div class="span3">
<h4>Powered by</h4>
<a href="http://framework.zend.com/" target="_blank"><img src="/img/stuff/zf2.png" /></a>
</div>
</div>
</div>
</footer>
