<?php
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Layout view script
 * 
 * @package    Application
 */

// set header
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));
$this->headLink()->prependStylesheet($this->basePath() . '/css/styles.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/font-awesome.min.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
$this->headLink()->appendAlternate($this->basePath() . '/blog/rss', 'application/atom+xml', 'RSS Feed');
$this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));
?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Zend Framework 2 Buch - Listings - Kapitel 3</title>
<?php echo $this->headMeta(); ?>
<meta name="description" content="">
<meta name="author" content="">
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>
</head>
<body>
<?php echo $this->header; ?>
<div class="container">
<div class="row">
<div class="span9">
<?php echo $this->content; ?>
</div>
<div class="span3 sidebar">
<?php echo $this->sidebar; ?>
</div>
</div>
</div>
<?php echo $this->footer; ?>
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<?php echo $this->inlineScript() ?>
</body>
</html>
