<?php
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Sidebar view script
 * 
 * @package    Application
 */
?>
<div class="well">
<div class="pull-center"><a href="http://www.galileocomputing.de/3460" target="_blank"><img src="/img/stuff/galileo-computing.gif"></a></div>
<p>Verlagswebsite mit Leseproben, Downloads, Bewertungen und mehr.</p>
<p class="pull-center"><a class="btn btn-primary" href="http://www.galileocomputing.de/3460" target="_blank">Zur Verlagswebsite &raquo;</a></p>
</div>
<div class="well">
<div class="pull-center"><a href="http://www.zendframeworkbuch.de/"><img src="/img/stuff/cover.jpg"></a></div>
<h4 class="pull-center">Buch Website</h4>
<p>Die Buchwebsite mit aktuellen Infos zum Buch, Blog &amp; Linkcodes.</p>
<p class="pull-center"><a class="btn btn-primary" href="http://www.zendframeworkbuch.de/">Zur Buch Website &raquo;</a></p>
</div>
<div class="well">
<p class="pull-center"><a href="http://www.zfforum.de/zend-framework-2-buch/" target="_blank"><img src="/img/stuff/zfforum.jpg"></a></p>
<p class="pull-center"><a class="btn btn-primary" href="http://www.zfforum.de/zend-framework-2-buch/" target="_blank">Zum Support Forum &raquo;</a></p>
</div>
<div class="well">
<p class="pull-center"><a target="_blank" href="http://www.zendframeworkschulung.de/"><img src="http://www.zendframeworkschulung.de/img/logo.png"></a></p>
<p>Stärken Sie Ihr Know-how und buchen Sie eine Zend Framework 2 Schulung in Ihrer Nähe.</p>
<p class="pull-center"><a class="btn btn-primary" target="_blank" href="http://www.zendframeworkschulung.de/">Zend Framework Schulung 2 »</a></p>
</div>
