<?php 
/**
 * ZF2 Buch Kapitel 3
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 3</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0301">Listing 3.1</a></td>
<td>Virtual Host Konfiguration für Linux</td>
</tr>
<tr>
<td><a href="/listing/listing0302">Listing 3.2</a></td>
<td>Virtual Host Konfiguration für Windows</td>
</tr>
<tr>
<td><a href="/listing/listing0303">Listing 3.3</a></td>
<td>Ausgabe nach der Installation von <code>Zend\View</code> mit Pyrus</td>
</tr>
<tr>
<td><a href="/listing/listing0304">Listing 3.4</a></td>
<td>Ausgabe nach der Installation von <code>Zend\Mvc</code> mit Pyrus</td>
</tr>
<tr>
<td><a href="/listing/listing0305">Listing 3.5</a></td>
<td><code>composer.json</code> Datei für die Installation ausgewählter Pakete</td>
</tr>
<tr>
<td><a href="/listing/listing0306">Listing 3.6</a></td>
<td>Ausgabe nach der Installation mit Composer</td>
</tr>
<tr>
<td><a href="/listing/listing0307">Listing 3.7</a></td>
<td><code>composer.json</code> Datei für die Installation des Gesamtpakets</td>
</tr>
<tr>
<td><a href="/listing/listing0308">Listing 3.8</a></td>
<td>Konfigurationsdatei für die eingesetzten Module der Anwendung</td>
</tr>
<tr>
<td><a href="/listing/listing0309">Listing 3.9</a></td>
<td>Frontcontroller-Datei der SkeletonApplication</td>
</tr>
<tr>
<td><a href="/listing/listing0310">Listing 3.10</a></td>
<td><code>/public/.htaccess</code> der SkeletonApplication</td>
</tr>
<tr>
<td><a href="/listing/listing0311">Listing 3.11</a></td>
<td><code>Module.php</code> der SkeletonApplication</td>
</tr>
<tr>
<td><a href="/listing/listing0312">Listing 3.12</a></td>
<td>Teil 1 der Konfigurationsdatei aus dem Application Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0313">Listing 3.13</a></td>
<td>Teil 2 der Konfigurationsdatei aus dem Application Modul</td>
</tr>
</tbody>
</table>
